version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:2022.07.1
    paralleism: 30
    steps:
      - checkout
      - run: |
            curl ipv4.icanhazip.com
            sudo apt-get update \
              --quiet
            DEBIAN_FRONTEND=noninteractive sudo apt-get install \
              --assume-yes \
              --no-install-recommends \
              --quiet \
              ca-certificates \
              git \
              golang-go \
              ssh-client \
              tzdata
