version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:8
    parallelism: 15
    steps:
      - checkout
      - run: |
            git fetch --all --tags
            git pull origin $(git rev-parse --abbrev-ref HEAD)
            apt update && apt install -y curl
            curl -sL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xA1715D88E1DF1F24" |  apt-key add
            apt update
            apt-get install software-properties-common -y
            add-apt-repository 'deb http://ppa.launchpad.net/git-core/ppa/ubuntu focal main'

            apt update
            apt-get install git -y
            echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
            echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
            curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
            apt update
            apt install -y sbt
